import { GUARDRAILS } from '@centopus/contracts';
import { Field, FieldsetTitle, Icon } from '@centopus/ui';
import type { RunFieldsProps } from './ProductFields';

export function ExecutionFields({ configuration, errors, update }: RunFieldsProps) {
  return <section className="form-section"><FieldsetTitle number="02" title="Session boundaries" description="Start small. Every session has explicit time, action, and budget limits." /><div className="execution-fields">
    <Field id="user_count" label="Synthetic users" hint="1–100 users" error={errors.user_count}><input id="user_count" type="number" min={1} max={GUARDRAILS.MAX_USERS} step={1} value={Number.isNaN(configuration.user_count) ? '' : configuration.user_count} onChange={e => update('user_count', e.target.valueAsNumber)} aria-invalid={Boolean(errors.user_count)} aria-describedby={`user_count-hint${errors.user_count ? ' user_count-error' : ''}`} required /></Field>
    <Field id="batch_size" label="Batch size" hint={`Up to ${GUARDRAILS.MAX_BATCH_SIZE} at a time`} error={errors.batch_size}><input id="batch_size" type="number" min={1} max={GUARDRAILS.MAX_BATCH_SIZE} step={1} value={Number.isNaN(configuration.batch_size) ? '' : configuration.batch_size} onChange={e => update('batch_size', e.target.valueAsNumber)} aria-invalid={Boolean(errors.batch_size)} aria-describedby={`batch_size-hint${errors.batch_size ? ' batch_size-error' : ''}`} required /></Field>
    <Field id="max_session_seconds" label="Session timeout" hint="Maximum 5 minutes" error={errors.max_session_seconds}><select id="max_session_seconds" value={configuration.max_session_seconds} onChange={e => update('max_session_seconds', Number(e.target.value))} aria-invalid={Boolean(errors.max_session_seconds)}><option value={60}>1 minute</option><option value={120}>2 minutes</option><option value={180}>3 minutes</option><option value={240}>4 minutes</option><option value={300}>5 minutes</option></select></Field>
  </div><div className="milestone-note"><Icon name="info" size={15} /><p>{configuration.user_count === 1 ? <><strong>One user is the right starting point.</strong> Prove one session before scaling to 5, 20, then 100.</> : <><strong>Scale after the first session works.</strong> The testing ladder is 1 → 5 → 20 → 100 users.</>}</p></div><div className="fixed-limits"><span><Icon name="cursor" size={13} />{GUARDRAILS.MAX_ACTIONS} actions / session</span><span><Icon name="retry" size={13} />{GUARDRAILS.MAX_RETRIES_SAME_STATE} retries / state</span></div></section>;
}
